# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: number_extractor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'number_extractor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16number_extractor.proto\"\x1c\n\x0c\x45xcelRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\" \n\rExcelResponse\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\x32I\n\x16NumberExtractorService\x12/\n\x0e\x45xtractNumbers\x12\r.ExcelRequest\x1a\x0e.ExcelResponseB \n\x1c\x63om.example.number_extractorP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'number_extractor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.example.number_extractorP\001'
  _globals['_EXCELREQUEST']._serialized_start=26
  _globals['_EXCELREQUEST']._serialized_end=54
  _globals['_EXCELRESPONSE']._serialized_start=56
  _globals['_EXCELRESPONSE']._serialized_end=88
  _globals['_NUMBEREXTRACTORSERVICE']._serialized_start=90
  _globals['_NUMBEREXTRACTORSERVICE']._serialized_end=163
# @@protoc_insertion_point(module_scope)
