# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tfibonacci\"\x1d\n\x10\x46ibonacciRequest\x12\t\n\x01n\x18\x01 \x01(\x05\"\x1f\n\x0e\x46ibonacciReply\x12\r\n\x05value\x18\x01 \x01(\x03\x32P\n\tFibonacci\x12\x43\n\tFibonacci\x12\x1b.fibonacci.FibonacciRequest\x1a\x19.fibonacci.FibonacciReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIBONACCIREQUEST']._serialized_start=28
  _globals['_FIBONACCIREQUEST']._serialized_end=57
  _globals['_FIBONACCIREPLY']._serialized_start=59
  _globals['_FIBONACCIREPLY']._serialized_end=90
  _globals['_FIBONACCI']._serialized_start=92
  _globals['_FIBONACCI']._serialized_end=172
# @@protoc_insertion_point(module_scope)
